server:
  port: 8081
  servlet:
    context-path: /luckmoney
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: fta
    client-auth: none #need 需要客户端验证证书；none客户端可以忽略证书


limit:
  minMoney: 0.01
  maxMoney: 9999
  description: 最少要发${limit.minMoney}元,最多${limit.maxMoney}元


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckmoney?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null