server:
  port: 8081
  servlet:
    context-path: /luckmoney
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: fta


limit:
  minMoney: 0.01
  maxMoney: 9999
  description: 最少要发${limit.minMoney}元,最多${limit.maxMoney}元


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckmoney?characterEncoding=utf-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null